# Generated by Django 5.2.12 on 2026-03-18 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WQSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='System 1', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.FloatField(default=1000.0)),
                ('temperature', models.FloatField(default=25.0)),
                ('salinity', models.FloatField(default=35.0)),
                ('initial_ph', models.FloatField(default=7.5)),
                ('initial_alk', models.FloatField(default=2.0)),
                ('target_ph', models.FloatField(default=8.2)),
                ('target_alk', models.FloatField(default=3.2)),
                ('tan', models.FloatField(default=1.0)),
                ('uia_limit', models.FloatField(default=0.02)),
                ('co2_limit', models.FloatField(default=15.0)),
                ('calcium', models.FloatField(default=412.0)),
                ('reagent1', models.CharField(default='nahco3', max_length=20)),
                ('reagent2', models.CharField(default='naoh', max_length=20)),
                ('show_uia', models.BooleanField(default=True)),
                ('show_co2', models.BooleanField(default=True)),
                ('show_omega', models.BooleanField(default=True)),
                ('show_adjust', models.BooleanField(default=True)),
                ('show_ph_major', models.BooleanField(default=True)),
                ('show_ph_minor', models.BooleanField(default=True)),
                ('dic_max', models.FloatField(default=6.0)),
                ('alk_max', models.FloatField(default=6.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wq_systems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
